### PR TITLE
Apple-Mimick

### PR DESCRIPTION
**Pull request by jdmartinez1062**

### CODE REVIEW

**Review by uche-inyama — COMMENTED** [review]
## Pull Request Under review by Inyama, Uchechukwu Henry

**Review by uche-inyama — COMMENTED** [review]
## Pull Request Under review by Inyama, Uchechukwu Henry

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Nice Job :clap: :+1: 
### Just a change and we a good to go.

- [ ]   ```  <span class="bottom-img-div fs left-img"></span>
                <span class="bottom-img-div fc "></span>
                <span class="bottom-img-div mac"></span>
                <span class="bottom-img-div supplier right-img"></span> ```
  ### Your ``` <span></span>``` tag for each image should be wrapped with  ```<a></a>``` tag. The images are links (to another articles or `#`)

### Implement this change and merge to the master branch

### Good Job! :medal_sports:

**Review by Oghenebrume50 — APPROVED** [review]
Hi @jdmartinez1062  Good Job, I see that you have implemented the requested changes, you can merge this to master now and continue on the next project, this is approved  :+1: 
Let's make more awesome projects like this :smile:

**Pull request merged**
